//
// Created by ksel on 19/06/24.
//

#ifndef MINIPROJEKT3_WARCABY_SRC_DRAUGHTS_ALGORITHM_LIB_H_
#define MINIPROJEKT3_WARCABY_SRC_DRAUGHTS_ALGORITHM_LIB_H_

#include "minmax/MinMax.h"

#endif  // MINIPROJEKT3_WARCABY_SRC_DRAUGHTS_ALGORITHM_LIB_H_
